FROM ubuntu:22.04 

ARG MIGRATION_SERVICE_WORKDIR

RUN apt update
RUN apt install -y ca-certificates curl gnupg

RUN mkdir -p /etc/apt/keyrings; \
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key \
      | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg; \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_18.x nodistro main" \ 
      | tee /etc/apt/sources.list.d/nodesource.list; \
    apt update; \
    apt install nodejs -y;

WORKDIR ${MIGRATION_SERVICE_WORKDIR}

COPY migration_service .
