name: animatrium
services: 
  api: 
    depends_on: 
      - db
    build:
      context: ../../
      dockerfile: ./docker/dev/Dockerfile.api
      args: 
        - API_WORKDIR=${API_WORKDIR}
    command: npm run dev
    ports:
      - 3001:${API_PORT}
    networks:
      primary:
    env_file:
      - .env
    volumes:
      - ../../api/src/:/${API_WORKDIR}/src/
    restart: "no"
  client:
    depends_on: 
      - api
    build:
      context: ../../
      dockerfile: ./docker/dev/Dockerfile.client
      args: 
        - CLIENT_WORKDIR=${CLIENT_WORKDIR}
    command: npm run dev
    ports:
      - 3000:${CLIENT_PORT}
    networks:
      primary:
    env_file:
      - .env
    volumes:
      - ../../client/src/:/${CLIENT_WORKDIR}/src/
    restart: "no"
  db:
    build:
      context: ../../
      dockerfile: ./docker/dev/Dockerfile.db
    command: mariadbd --port ${DB_PORT}
    networks:
      primary:
    env_file:
      - .env
    volumes:
      - data:/var/lib/mysql
    restart: "no"
networks:
  primary: {}
volumes:
  data: {}
