services: 
  next:
    build:
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - 3000:80
    networks:
      animatrium:
        aliases:
          - next
    env_file:
      - .env.dev
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    networks:
      animatrium:
        aliases:
          - db
    volumes:
      - data:/var/lib/mysql
    env_file:
      - .env.dev
networks:
  animatrium: {}
volumes:
  data: {}
